[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#3E5363"
backgroundColor = "#F3EEE4"
secondaryBackgroundColor = "#FCFAF6"
textColor = "#1C1915"
font = "serif"
